name: Java CI with Gradle and Docker

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Make Gradle executable
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Rename JAR
      run: mv build/libs/*.jar build/libs/app.jar

    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t anisa2d6/webapp:latest .

    - name: Push Docker Image
      run: docker push anisa2d6/webapp:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull anisa2d6/webapp:latest
          docker stop webapp || true
          docker rm webapp || true
          docker run -d -p 8080:8080 --name webapp anisa2d6/webapp:latest
